name: badminton
root_dir: /content/badminton_data/badminton
video_dirname: video
frame_dirname: frame
csv_dirname: csv
train:
  matches : []
  num_clip_ratio: 1.0
test:
  matches: ['test_match1', 
            'test_match2', 
            'test_match3']
  num_clip_ratio: 1.0
